# Dream 100 Keyword Engine - Supabase Configuration
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54321
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324
ip_version = "IPv4"

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[analytics]
enabled = false
port = 54327
vector_port = 54328
# In production, set this to false for security
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions]
verify_jwt = false

[edge_runtime]
enabled = true
ip_version = "IPv4"

# Database settings specific to Dream 100 Keyword Engine
[auth.hook.custom_access_token]
enabled = false

# Enable pgvector extension for embedding similarity search
[db.extensions]
enabled = ["pgvector", "uuid-ossp", "pgcrypto"]

# Performance settings for handling 10k+ keywords
[db.settings]
max_connections = 100
shared_preload_libraries = "pg_stat_statements,auto_explain"
max_worker_processes = 4
max_parallel_workers = 4
max_parallel_workers_per_gather = 2
work_mem = "64MB"
maintenance_work_mem = "256MB"
effective_cache_size = "1GB"
shared_buffers = "256MB"
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging for performance monitoring
log_statement = "none"
log_min_duration_statement = 1000
log_checkpoints = true
log_connections = false
log_disconnections = false

# Security settings
ssl = true
password_encryption = "scram-sha-256"